### ISSUE TITLE
App is blank when running on android device

### ISSUE THREAD

**Issue by polcham** [crosswalk-project/cordova-plugin-crosswalk-webview#134]
Hi, 

I am encountering a blank app when running the app on Android device using Genymotion emulator. Please see screenshot below.
If I remove the Crosswalk plugin, then the app is working properly. 
I am using Ionic 3 and Genymotion, if that matters.
![screen shot 2017-04-29 at 1 36 44 pm](https://cloud.githubusercontent.com/assets/10678997/25553278/ab14860e-2ce1-11e7-97f7-683ab2834b2e.png)

**Comment by mcfarljw** [comment]
This is the same as #118 and doesn't seem to have a fix yet. It seems to be related to using the plugin with x86 device emulators. If you use the plugin and push it to an ARM device then it should work just fine.

**Comment by matthewlloyd** [comment]
Adding --disable-gpu-rasterization to the Crosswalk command line (xwalkCommandLine preference in config.xml) fixed this for me. YMMV.
