### ISSUE TITLE
Disable Crosswalk for iOS

### ISSUE THREAD

**Issue by Mr-Anonymous** [crosswalk-project/cordova-plugin-crosswalk-webview#144]
I have an Ionic App and I mainly want to use Crosswalk for Android platform. However, when I install `cordova-plugin-crosswalk-webview` plugin, it also includes the plugin for iOS platform and its gets installed to my iOS App when adding the platform like this:

```
Installing "cordova-plugin-crosswalk-webview" for ios

        After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.

        So the minSdkVersion of Cordova project is configured to 16 by default.
```

How can install this plugin and use it only for Android and not for iOS? Is there a setting in `config.xml` I can add for this?

**Comment by menelike** [comment]
Ideally it is possible to switch between crosswalk and webview depending on arguments like minAndroidVersion, minIosVersion etc.
Also this would a migration away from crosswalk a lot easier.

**Comment by Mr-Anonymous** [comment]
Thank you @menelike 

I installed the WKwebview plugin today without removing the Crosswalk plugin nor adding the minIosVersion setting in config and it seems to be working so far. My plan is to use Crosswalk for Android and WKwebview for iOS. So far it seems to work.

Thank you for your comment. I appreciate that.

**Comment by Mr-Anonymous** [comment]
I am still confused if this plugin supports iOS or not. because reading through the old tickets here, I see that iOS support was added on Feb 2016 ( https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/81 ) and then it was reverted on March 2016 ( https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/87 ). But when I add iOS platform after installing this plugin, it shows the message: `Installing "cordova-plugin-crosswalk-webview" for ios`. So Is this crosswalk plugin support and provide a WebView for iOS or not? Its confusing since it doesnt mention anything in the installation instructions here but I see that the plugin is getting installed in iOS when I run `ionic platform add ios`.  If its only for Android, then why am I seeing this message when I add iOS platform?

**Comment by menelike** [comment]
@Mr-Anonymous 

There seems to be a misunderstanding ;), I just made a suggestion that such a feature would be appreciated, unfortunately such a functionality like `minAndroidVersion`, `minIosVersion` etc. does not exist yet.

I also requested this here https://github.com/crosswalk-community/crosswalk/issues/1 but I'm not hoping for an implementation, and at this point I'm not even sure if this is possible anyway.

Your goal seems to be more doable as you can just remove cordova completely from iOS project before you start the build. Remove crosswalk from you plugin list and then build your project. This should actually work, doesn't it?

**Comment by Mr-Anonymous** [comment]
@menelike that makes sense. Thanks for clarifying that. :)

Cheers,
Neel.
