### ISSUE TITLE
unable to build ionic app with crosswalk

### ISSUE THREAD

**Issue by arnoldparge** [crosswalk-project/cordova-plugin-crosswalk-webview#160]
installing crosswalk:

> cordova plugin add cordova-plugin-crosswalk-webview
> Unmet project requirements for latest version of cordova-plugin-crosswalk-webview:
>     cordova (0.0.1 in project, >=5.2.0 required)
> Fetching highest version of cordova-plugin-crosswalk-webview that this project supports: 1.8.0 (latest is 2.3.0)
> Installing "cordova-plugin-crosswalk-webview" for android
> Subproject Path: CordovaLib
> Saved plugin info for "cordova-plugin-crosswalk-webview" to config.xml
> Adding cordova-plugin-crosswalk-webview to package.json
> 

I get this below error:

> Error: cmd: Command failed with exit code 1 Error output:
> C:\Users\PARGE\Documents\ionic\cross\platforms\android\src\org\crosswalk\engine\XWalkWebViewEngine.java:55: error: XWalkWebViewEngine is not abstract and does not override abstract method evaluateJavascript(String,ValueCallback<String>) in CordovaWebViewEngine
> public class XWalkWebViewEngine implements CordovaWebViewEngine {
>        ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileArmv7ReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 

ionic info:

> cli packages: (C:\Users\PARGE\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.9.2
>     ionic (Ionic CLI) : 3.9.2
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.3
>     Ionic Framework    : ionic-angular 3.6.0
> 
> System:
> 
>     Node : v8.1.2
>     npm  : 5.0.3
>     OS   : Windows 10

**This issue is related to Crosswalk not Ionic**

**Comment by iancoutinho** [comment]
I seem to be receiving the same issue, tried to run the command "ionic run android" and got the followng error:

ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk\android-sdk

JAVA_HOME=C:\Program Files\java\jdk1.8.0_131

Subproject Path: CordovaLib

null


google-services plugin could not detect any version for com.google.android.gms o
r com.google.firebase, default version: 9.0.0 will be used.


please apply google-services plugin at the bottom of the build file.


org.xwalk:xwalk_core_library:23+


Incremental java compilation is an incubating feature.



FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23+.
     Required by:
         :android:unspecified



> Could not resolve org.xwalk:xwalk_core_library:23+.


> Failed to list versions for org.xwalk:xwalk_core_library.
            >
Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/c
rosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.

BUILD FAILED

Total time: 26.822 secs


               > Could not GET 'https://download.01.org/crosswalk/releases/cross
walk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received s
tatus code 503 from server: Service Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23+.
     Required by:
         :android:unspecified
      > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crossw
alk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadat
a.xml.
               > Could not GET

'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

I tried opening the link manually but the page displays:
An error occurred while processing your request.
Reference #30.f7e5f33f.1504522090.155f6436

Any solution to this would be much appreciated.

**Comment by rakuco** [comment]
We're tracking this in #158 (I've also sent a message to our mailing lists). The tl;dr is that download.01.org is currently down and we're working to get it back up.
