### ISSUE TITLE
Error cordova-plugin-crosswalk-webview version 2.4.0

### ISSUE THREAD

**Issue by stove654** [crosswalk-project/cordova-plugin-crosswalk-webview#194]
Hi, i saw project update version 2.4.0 fixed cordova android 7.0.0 build, i'm using `cordova plugin add cordova-plugin-crosswalk-webview@2.4.0 --save` cannot get it.
`npm ERR! notarget No compatible version found: cordova-plugin-crosswalk-webview@2.4.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.3.0, 2.2.0, 2.1.0, 2.0.0, 1.8.0, 1.7.2, 1.7.1, 1.7.0, 1.6.1, 1.6.0, 1.5.0, 1.4.0, 1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.0` 
Can you help me. Thanks.

**Comment by baleboy** [comment]
The 2.4.0 version is not yet released to npm

**Comment by Bartinger** [comment]
What are the plans on releasing 2.4.0 to npm?

**Comment by baleboy** [comment]
we are doing our best to get it out this week.

**Comment by lishengsong** [comment]
ionic I used crosswalk # 2.3.0 and added <preference name = "CrosswalkAnimatable" value = "true" />. Flashback in android7.0, and reported the error message java.lang.UnsupportedOperationException: TextureView does not support displaying a background drawable, etc., how to solve ah, seeking help

**Comment by kaynz** [comment]
It has been published.

**Comment by baleboy** [comment]
Yes :) For some reason the README in npm.js is not updated, but everything else seems to be fine.

**Comment by baleboy** [comment]
@kaynz do you have a twitter handle? We'd like to give you credit when we announce the fix.

**Comment by kaynz** [comment]
@baleboy yes: https://twitter.com/k4ynz

**Comment by lishengsong** [comment]
ot implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
01-25 08:52:24.361 17812-17812/com.gree.internal.mall E/chromium: [ERROR:xwalk_browser_context.cc(88)] Failed to read preference, error num: 0
01-25 08:52:24.364 17812-17812/com.gree.internal.mall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.gree.internal.mall, PID: 17812
                                                                        java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
