### ISSUE TITLE
Today, I got an Error with nothing modified

### ISSUE THREAD

**Issue by HelkeNarmo** [crosswalk-project/cordova-plugin-crosswalk-webview#204]
```
Error: /Users/zhengjihan/sxun/temp/cloudcontry/build_env/cordova_project/platforms/android/gradlew: Command failed with exit code 1 Error output:
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7ReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

Today, I run 'cordova build android' just as yesterday, only updated some files in 'www', and that Error  occurred.

So I try to find out what happend, but there is few anwser told that was caused by 'support-v4:+'

when I remove this plugin from my project, it can build, but when I add this plugin to my project then cause that Error again.

please help me.

**Comment by puny-d** [comment]
I have the same problem

**Comment by Scuttman** [comment]
I have the same problem. Literally was working one minutes, I edited a ts file and ran again and since then I have spent hours trying fixes and none are succeeding. Apparently there is a breaking update on the com.android.support:support-v4:28 but I can't find anyway of forcing the plugin to use an earlier version. Any ideas, I was a couple of hours away from publishing!!!

**Comment by thebookgy** [comment]
I have the same problem too

**Comment by sukprasert** [comment]
I have the same problem too

**Comment by senson2018** [comment]
I have the same problem too

**Comment by muhammedtanriverdi** [comment]
Same problem! There is a discussion also here: https://stackoverflow.com/questions/49162538/cordova-build-android-unable-to-find-attribute-androidfontvariationsettings-a

**Comment by UNUMobile** [comment]
I have same problem, but I add this script to platforms/android/build.gradle, it's work for me!

configurations.all {
resolutionStrategy.force 'com.android.support:support-v4:24.0.0'
}

**Comment by muhammedtanriverdi** [comment]
It's strange, but it works when I add the above lines with the same versions.
This is my related lines in build.gradle file:

`dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.android.support:support-v4:26.+"
    compile "com.android.support:appcompat-v7:26.+"
    // SUB-PROJECT DEPENDENCIES END
}

// ADDED THESE LINES
configurations.all {
    resolutionStrategy.force 'com.android.support:support-v4:26+'
}`

**Comment by sadjous** [comment]
thank you, @UNUMobile and @muhammedtanriverdi  solution worked for me

**Comment by GBoll** [comment]
The two attributes referenced in the error did not even exist in my project folders until today. Furthermore, the two attributes are duplicated in the same tag. 

Please refer to my [description of the isolated problem](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205)

**Comment by Scuttman** [comment]
Thank You @UNUMobile! A perfect solution. Fixed the problem straight away. Thank you for contributing.

**Comment by henkkelder** [comment]
Its a duplicate entry in values.xml in a folder called "support-compat-28.0.0-alpha1.aar". 
You'll find this file on windows at \users\YOURUSERID\.gradle\caches\transforms-1\files-1.1.

Once inside that folder you have to go some levels deeper to 'values.xml'.
In that file, search for an element <declare-styleable name="FontFamilyFont">

In that element, remove the FOUR lines with "android:" in it

After I made that change I can build again without errors.

**Comment by GBoll** [comment]
@henkkelder I think you got to the origin of it.

Anyone know how to reach the same on a Mac? 

/Users/harddrive/.gradle/caches/transforms-1
contains only the file transforms-1.lock

**Comment by rafiqvns** [comment]
@muhammedtanriverdi  and @UNUMobile

Thanks :)

**Comment by rakuco** [comment]
Since #205 has narrowed the problem down and offered a few suggestions on how to fix the bug, I'm closing this issue and pointing everyone to #205.

**Comment by yushaUzumo** [comment]
It solves the issue for me as well (thanks) but no one explains what the lines 

resolutionStrategy.force 'com.android.support:support-v4:24.0.0'

resolutionStrategy.force 'com.android.support:support-v4:26+'

resolutionStrategy.force 'com.android..support:support-v4:27.1.0'

mean. What do they mean? and which one to use when? Please teach us to fish rather than giving us a fish.

**Comment by kennyalmendral** [comment]
Thanks @UNUMobile

**Comment by 007vel** [comment]
Resolved me follow th link [https://youtube.com/watch?v=oBsbI8ICYKg&feature=youtu.be]

**Comment by noyessie** [comment]
> It's strange, but it works when I add the above lines with the same versions.
> This is my related lines in build.gradle file:
> 
> `dependencies {
> compile fileTree(dir: 'libs', include: '*.jar')
> // SUB-PROJECT DEPENDENCIES START
> debugCompile(project(path: "CordovaLib", configuration: "debug"))
> releaseCompile(project(path: "CordovaLib", configuration: "release"))
> compile "com.android.support:support-v4:26.+"
> compile "com.android.support:appcompat-v7:26.+"
> // SUB-PROJECT DEPENDENCIES END
> }
> 
> // ADDED THESE LINES
> configurations.all {
> resolutionStrategy.force 'com.android.support:support-v4:26+'
> }`

Hi,

I'm new on ionic cordova. Please in wich file and section should i put it?
