### ISSUE TITLE
Installation error on fresh cordova project

### ISSUE THREAD

**Issue by rizkyramadhan** [crosswalk-project/cordova-plugin-crosswalk-webview#210]
Well, I know this project is unmaintaned, but each solution including cordova own webview is so unrealiable....

step to reproduct:

`
yarn global install cordova
cordova create hello org.hello hello
cd hello
cordova platform add android
cordova plugin add cordova-plugin-crosswalk-webview
cordova run android
`

And, here is the error: 

`:processArmv7DebugResourcesERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
 FAILED
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

BUILD FAILED

Total time: 2 mins 55.18 secs`

**Comment by rakuco** [comment]
See #205.
