### ISSUE TITLE
Cannot build, missing support-annotations.jar

### ISSUE THREAD

**Issue by BenjaminKauer** [crosswalk-project/cordova-plugin-crosswalk-webview#222]
Hi folks,

I'm getting the following error when trying to build my app:

```
A problem occurred configuring root project 'android'.
> Could not find support-annotations.jar (com.android.support:support-annotations:28.0.0-alpha1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-annotations/28.0.0-alpha1/support-annotations-28.0.0-alpha1.jar
```

You can open that URL, sometimes it fails with HTTP 404, sometimes it does work. When building my app it always fails, which renders me unable to build my app at all.

Any ideas on how to resolve that?

I'm using XWalk 2.4.0 and Cordova 6.5.0, updated Android Support Repo via SDK Manager.

Kind regards
Benjamin Kauer

**Comment by crashd0wn** [comment]
I'm having a similar problem since today, and it's really bad since I'm unable to deploy a new version of the app...

```
A problem occurred configuring root project 'android'.
> Could not find common.jar (android.arch.core:common:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar
```

Any idea as to why this is not available anymore on jcenter, is there are any other repository we can use and if so: where to configure it??

**Comment by BenjaminKauer** [comment]
@crashd0wn it IS available on jcenter, sometimes. I can call that URL via Chrome. Sometimes it downloads the file, sometimes I get an 404. So it seems to be an issue with jcenters/bintrays webserver.

Anyways, is there any way to configure another repo / point to a locally stored file?

**Comment by BenjaminKauer** [comment]
I solved it by upgrading cordova-android to 7.0.0. This change sets the Android MinSDKVersion to 19 (Android 4.4.+), tho.

**Comment by Yaghiyah** [comment]
I'm getting the same problem unfortunately i cannot just upgrade as suggested by @BenjaminKauer 

Please help.

> support for subdirectories is deprecated and will be removed in Cordova@7
> Fetching plugin "https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview" via git clone
> Repository "https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview" checked out to git ref "2.2.0".
> Installing "cordova-plugin-crosswalk-webview" for android
> ANDROID_HOME=C:\ANDROID_SDK
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
> Subproject Path: CordovaLib
> Incremental java compilation is an incubating feature.
> WARNING: Module 'com.android.support:support-v4:28.0.0-alpha1' depends on one or more Android Libraries but is a jar
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not find support-v4.jar (com.android.support:support-v4:28.0.0-alpha1).
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/android/support/support-v4/28.0.0-alpha1/support-v4-28.0.0-alpha1.jar
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 2.534 secs

**Comment by BenjaminKauer** [comment]
We've downgraded to `cordova-android` version 6.4.0 and everything is working like a charm.
