### ISSUE TITLE
Appium support?

### ISSUE THREAD

**Issue by egorvas** [crosswalk-project/cordova-plugin-crosswalk-webview#229]
Hi, Id like to configure appium tests with meteor android application (also has crosswalk webview).
When I build my app with a command like `meteor --verbose --debug build ~ --server https://...` I expect that I will be able to run appium tests on this app.

But after tests running appium show me this error:

> [Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*2024
> [Chromedriver]   (make sure the app has its WebView configured for debugging)
> [Chromedriver]   (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64))
> [Chromedriver]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
> [Chromedriver]     at Chromedriver.callee$2$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:411:13)
> [Chromedriver]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
> [Chromedriver]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [Chromedriver]     at <anonymous>
> [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM

On the base android webview this issue can be solved by command WebView.setWebContentsDebuggingEnabled(true), but how can I do it with crosswalk webview?

**Comment by markoplatogo** [comment]
https://github.com/blutter/appium-crosswalk-fix

**Comment by egorvas** [comment]
@markoplatogo thanks for this info. Issue closed.
