### ISSUE TITLE
Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.

### ISSUE THREAD

**Issue by dyywork** [crosswalk-project/cordova-plugin-crosswalk-webview#241]
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:24+.
     Required by:
         :android:unspecified
      > Could not resolve org.xwalk:xwalk_core_library:24+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status co
de 504 from server: Gateway Time-out

**Comment by rakuco** [comment]
This looks like a temporary problem, and 01.org is up and running.

**Comment by nevillekatila** [comment]
It's down again. It seems to be very unreliable. Any work aounds for this?

**Comment by dyywork** [comment]
The problem has been solved. Thank you.
