### ISSUE TITLE
Could not resolve org.xwalk:xwalk_core_library:23+. Response 504

### ISSUE THREAD

**Issue by vasyldinets** [crosswalk-project/cordova-plugin-crosswalk-webview#242]
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23+.
     Required by:
         project :
      > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

**Comment by asalazar1212** [comment]
+1

**Comment by teraholic** [comment]
Me too.
https://crosswalk-project.org/ also has no response. "504 Gateway Time-out" will be returned.

**Comment by Le2e** [comment]
Did they finally pull the plug? Site is gone, can't download from maven

**Comment by rakuco** [comment]
It was a temporary failure, everything's back up now.
