### ISSUE TITLE
Apache Cordova plugin registry

### ISSUE THREAD

**Issue by dhatawesomedude** [crosswalk-project/cordova-plugin-crosswalk-webview#30]
I am excited about this plugin, I build my app via phonegap remote build which only allows phonegap plugins or plugins from the apache cordova plugin registry.

I am wondering if crosswalk plans to upload this plugin to the apache cordova plugin registry.

**Comment by huningxin** [comment]
As http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html, we published it to npm (https://www.npmjs.com/package/cordova-plugin-crosswalk-webview). This plugin depends on Cordova -Android 4.0+. I am sure whether phonegap remote build support it or not.
